### ISSUE TITLE
Program does not work

### ISSUE THREAD

**Issue by ghost** [Molodejka/UniversalConstantDumper#2]
Whenever i attempt to dump a script, i get this error.
`Rextester api calls require api key. To get one please visit https://www.patreon.com/rextester`
![image](https://user-images.githubusercontent.com/86860344/126014929-aba1112a-7052-45f5-9f78-44d84f397600.png)
is there a way to fix it?

**Comment by 0x09B** [comment]
You need to change API so I won't do it.
